---
title: "GGPLOT2 Lesson Challenges Solutions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Solution Challenge 1

```{r, eval=FALSE}
ggplot(data = gapminder, aes(x = year, y = lifeExp)) + geom_point()
```

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch1-sol-1.png

---


## Solution Challenge 2

```{r, eval=FALSE}
ggplot(data = gapminder, aes(x = year, y = lifeExp, color=continent)) +
  geom_point()
```

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch2-sol-1.png

---


##  Solution Challenge 3

```{r, eval=FALSE}
ggplot(data = gapminder, aes(x=year, y=lifeExp, by=country)) +
 geom_point() + geom_line(aes(color=continent))
```
* The lines now get drawn over the points!

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch3-sol-1.png

previous example:
http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-lifeExp-layer-example-1-1.png


---


##  Solution Challenge 4a
```{r, eval=FALSE}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp)) +
 geom_point(size=3, color="orange") + scale_x_log10() +
 geom_smooth(method="lm", size=1.5)
```

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch4a-sol-1.png


---

##  Solution Challenge 4b

```{r, eval=FALSE}
ggplot(data = gapminder, aes(x = gdpPercap, y = lifeExp, color = continent)) +
geom_point(size=3, pch=17) + scale_x_log10() +
geom_smooth(method="lm", size=1.5)
```

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch4b-sol-1.png

---

##  Solution Challenge 5

```{r, eval=FALSE}
ggplot(data = gapminder, aes(x = gdpPercap, fill=continent)) +
 geom_density(alpha=0.6) + facet_wrap( ~ year) + scale_x_log10()
```

http://swcarpentry.github.io/r-novice-gapminder/fig/rmd-08-ch5-sol-1.png